<a href="https://colab.research.google.com/github/Isha1600/Python_Core_Practice/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [3]:
import numpy as np

a = np.array([10,20,30,40])

print(a.ndim)

1


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


In [5]:
a = np.array([1,2,3])
print(a * 2)

[2 4 6]


In [6]:
matrix = np.array([[1,2,3],
                   [4,5,6]])

print(matrix)

[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np
a = np.array([10, 20, 30, 40])
print(a)
print(a * 3)

[10 20 30 40]
[ 30  60  90 120]


In [8]:
a = np.array([5, 10, 15])
b = np.array([2,4,6])
print(a)
print(b)
print(a + b)

[ 5 10 15]
[2 4 6]
[ 7 14 21]


In [9]:
matrix = np.array([[1,2],
                   [3,4]])
print(matrix)
print(5 * matrix)

[[1 2]
 [3 4]]
[[ 5 10]
 [15 20]]


In [10]:
b = np.array([[1,2,3],
              [4,5,6]])

print(b.ndim)
print(b.shape)

2
(2, 3)


In [11]:
c = np.array([[1,2],
              [3,4],
              [5,6]])

print(c.shape)

(3, 2)


In [12]:
a = np.array([1,2,3,4])

print(a.dtype)

int64


In [13]:
a = np.array([1.5,2.5,3.5])

print(a.dtype)

float64


In [14]:
a = np.zeros(5)

print(a)

[0. 0. 0. 0. 0.]


In [15]:
b = np.zeros((3,4))

print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
a = np.ones(4)

print(a)

[1. 1. 1. 1.]


In [17]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
a = np.arange(1,10)

print(a)

[1 2 3 4 5 6 7 8 9]


In [19]:
a = np.arange(0,20,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18]


In [20]:
a = np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [21]:
c = np.array([5 , 10, 15, 20])
print(c)

print(c.ndim)
print(c.shape)
print(c.dtype)

[ 5 10 15 20]
1
(4,)
int64


In [22]:
d = np.array([[2,4],
             [6,8]])
print(d)

print(d.ndim)
print(d.shape)
print(d.dtype)

[[2 4]
 [6 8]]
2
(2, 2)
int64


In [23]:
c = np.zeros((4,3))
print(c)
print(c.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(4, 3)


In [24]:
import numpy as np

a = np.arange(5, 31, 5)
print(a)

[ 5 10 15 20 25 30]


In [25]:
import numpy as np

b = np.linspace(0, 12, 6)
print(b)

[ 0.   2.4  4.8  7.2  9.6 12. ]


In [26]:
import numpy as np

a = np.array([5,10,15,20])
print(a)

[ 5 10 15 20]


In [27]:
b = np.array([[1,2,3],
              [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [28]:
c = np.array([
    [[1,2],
     [3,4]],

    [[5,6],
     [7,8]]
])
print(c)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
import numpy as np

a = np.array([10,20,30,40])
print(a)
print(a[0])
print(a[2])
print(a[-1])

[10 20 30 40]
10
30
40


In [30]:
a = np.array([10,20,30,40,50])
print(a)
print(a[1:4])
print(a[0:5:2])

[10 20 30 40 50]
[20 30 40]
[10 30 50]


In [31]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b)
print(b[0,1])
print(b[1,2])
print(b[0])
print(b[:,1])

[[1 2 3]
 [4 5 6]]
2
6
[1 2 3]
[2 5]


In [32]:
import numpy as np

a = np.array([5, 10, 15, 20, 25])
print("Array:", a)
print("First element:", a[0])
print("Last element:", a[-1])

Array: [ 5 10 15 20 25]
First element: 5
Last element: 25


In [33]:
print(a[1:4])

[10 15 20]


In [34]:
b = np.array([[2, 4, 6],
              [8, 10, 12]])
print(b)
print(b[1,0])

[[ 2  4  6]
 [ 8 10 12]]
8


In [35]:
print(b[:,1])

[ 4 10]


In [36]:
import numpy as np

marks = np.array([45, 67, 89, 32, 76, 50])
print(marks)
print(np.max(marks))
print(np.mean(marks))
print(np.min(marks))
print(np.sum(marks))

[45 67 89 32 76 50]
89
59.833333333333336
32
359


In [37]:
numbers = [1,2,3,4]

result = []

for n in numbers:
    result.append(n*2)

print(result)

[2, 4, 6, 8]


In [38]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(a*2)

[1 2 3 4]
[2 4 6 8]


In [39]:
a = np.array([10,20,30])
print(a)
print(a+5)

[10 20 30]
[15 25 35]


In [40]:
print(a*3)
print(a/10)

[30 60 90]
[1. 2. 3.]


In [41]:
marks = np.array([45, 67, 89, 32])
print(marks+5)

[50 72 94 37]


In [42]:
a = np.array([1,2,3,4])

print(np.square(a))
print(np.sqrt(a))
print(np.exp(a))

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [43]:
marks = np.array([45,67,89,32])
print(marks>50)
print(marks[marks>50])

[False  True  True False]
[67 89]


In [44]:
b = np.array([5,10,15,20])
print(b+5)

[10 15 20 25]


In [45]:
a = np.array([4, 9, 16, 25])
print(np.sqrt(a))

[2. 3. 4. 5.]


In [47]:
marks = np.array([45,67,32,90,50])
print(marks[marks>60])

[67 90]


In [48]:
b = np.array([2,4,6,8])
print(b*3)

[ 6 12 18 24]


In [49]:
import numpy as np

a = np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [50]:
import numpy as np

marks = np.array([
    [80,75],
    [60,55],
    [90,85]
])

print(marks)

[[80 75]
 [60 55]
 [90 85]]


In [51]:
print(marks.shape)

(3, 2)


In [52]:
print(marks[0][0])

80


In [53]:
print(marks[2][1])

85


In [56]:
print(marks[0])
print(marks[:,0])
print(marks[:,1])

[80 75]
[80 60 90]
[75 55 85]


In [59]:
print(np.mean(marks))
print(np.mean(marks,axis = 0))
print(np.mean(marks,axis = 1))

74.16666666666667
[76.66666667 71.66666667]
[77.5 57.5 87.5]


In [60]:
a = np.array([1,2,3,4,5,6])

b = a.reshape(2,3)

print(b)

[[1 2 3]
 [4 5 6]]


In [62]:
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [64]:
a = np.array([10,20,30,40,50,60])
b = a.reshape(3,2)
print(b)

[[10 20]
 [30 40]
 [50 60]]


In [65]:
import numpy as np

dataset = np.array([
    [45,50],
    [60,65],
    [80,85]
])

print("Dataset:\n", dataset)

Dataset:
 [[45 50]
 [60 65]
 [80 85]]


In [66]:
print("Second student's marks:", dataset[1])

Second student's marks: [60 65]


In [67]:
print("First column of the dataset:", dataset[:, 0])

First column of the dataset: [45 60 80]


In [68]:
import numpy as np

average_marks_per_student = np.mean(dataset, axis=1)
print("Average marks of each student:", average_marks_per_student)

Average marks of each student: [47.5 62.5 82.5]


In [69]:
import numpy as np
data = np.array([
    [18,3,65],
    [19,4,70],
    [20,6,85],
    [21,5,80]
])

print(data)

[[18  3 65]
 [19  4 70]
 [20  6 85]
 [21  5 80]]


In [70]:
X = data[:,0:2]

print(X)

[[18  3]
 [19  4]
 [20  6]
 [21  5]]


In [71]:
y = data[:,2]

print(y)

[65 70 85 80]
