<a href="https://colab.research.google.com/github/Isha1600/Python_Core_Practice/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [ ]:
import numpy as np

a = np.array([10,20,30,40])

print(a.ndim)

1


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


In [ ]:
a = np.array([1,2,3])
print(a * 2)

[2 4 6]


In [ ]:
matrix = np.array([[1,2,3],
                   [4,5,6]])

print(matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
a = np.array([10, 20, 30, 40])
print(a)
print(a * 3)

[10 20 30 40]
[ 30  60  90 120]


In [ ]:
a = np.array([5, 10, 15])
b = np.array([2,4,6])
print(a)
print(b)
print(a + b)

[ 5 10 15]
[2 4 6]
[ 7 14 21]


In [ ]:
matrix = np.array([[1,2],
                   [3,4]])
print(matrix)
print(5 * matrix)

[[1 2]
 [3 4]]
[[ 5 10]
 [15 20]]


In [ ]:
b = np.array([[1,2,3],
              [4,5,6]])

print(b.ndim)
print(b.shape)

2
(2, 3)


In [ ]:
c = np.array([[1,2],
              [3,4],
              [5,6]])

print(c.shape)

(3, 2)


In [ ]:
a = np.array([1,2,3,4])

print(a.dtype)

int64


In [ ]:
a = np.array([1.5,2.5,3.5])

print(a.dtype)

float64


In [ ]:
a = np.zeros(5)

print(a)

[0. 0. 0. 0. 0.]


In [ ]:
b = np.zeros((3,4))

print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
a = np.ones(4)

print(a)

[1. 1. 1. 1.]


In [ ]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
a = np.arange(1,10)

print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
a = np.arange(0,20,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18]


In [ ]:
a = np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
c = np.array([5 , 10, 15, 20])
print(c)

print(c.ndim)
print(c.shape)
print(c.dtype)

[ 5 10 15 20]
1
(4,)
int64


In [ ]:
d = np.array([[2,4],
             [6,8]])
print(d)

print(d.ndim)
print(d.shape)
print(d.dtype)

[[2 4]
 [6 8]]
2
(2, 2)
int64


In [ ]:
c = np.zeros((4,3))
print(c)
print(c.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(4, 3)


In [ ]:
import numpy as np

a = np.arange(5, 31, 5)
print(a)

[ 5 10 15 20 25 30]


In [ ]:
import numpy as np

b = np.linspace(0, 12, 6)
print(b)

[ 0.   2.4  4.8  7.2  9.6 12. ]


In [ ]:
import numpy as np

a = np.array([5,10,15,20])
print(a)

[ 5 10 15 20]


In [ ]:
b = np.array([[1,2,3],
              [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([
    [[1,2],
     [3,4]],

    [[5,6],
     [7,8]]
])
print(c)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
import numpy as np

a = np.array([10,20,30,40])
print(a)
print(a[0])
print(a[2])
print(a[-1])

[10 20 30 40]
10
30
40


In [ ]:
a = np.array([10,20,30,40,50])
print(a)
print(a[1:4])
print(a[0:5:2])

[10 20 30 40 50]
[20 30 40]
[10 30 50]


In [ ]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b)
print(b[0,1])
print(b[1,2])
print(b[0])
print(b[:,1])

[[1 2 3]
 [4 5 6]]
2
6
[1 2 3]
[2 5]


In [ ]:
import numpy as np

a = np.array([5, 10, 15, 20, 25])
print("Array:", a)
print("First element:", a[0])
print("Last element:", a[-1])

Array: [ 5 10 15 20 25]
First element: 5
Last element: 25


In [ ]:
print(a[1:4])

[10 15 20]


In [ ]:
b = np.array([[2, 4, 6],
              [8, 10, 12]])
print(b)
print(b[1,0])

[[ 2  4  6]
 [ 8 10 12]]
8


In [ ]:
print(b[:,1])

[ 4 10]


In [ ]:
import numpy as np

marks = np.array([45, 67, 89, 32, 76, 50])
print(marks)
print(np.max(marks))
print(np.mean(marks))
print(np.min(marks))
print(np.sum(marks))

[45 67 89 32 76 50]
89
59.833333333333336
32
359


In [ ]:
numbers = [1,2,3,4]

result = []

for n in numbers:
    result.append(n*2)

print(result)

[2, 4, 6, 8]


In [ ]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(a*2)

[1 2 3 4]
[2 4 6 8]


In [ ]:
a = np.array([10,20,30])
print(a)
print(a+5)

[10 20 30]
[15 25 35]


In [ ]:
print(a*3)
print(a/10)

[30 60 90]
[1. 2. 3.]
